### PR TITLE
v1.5.0

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by sonnyp** [comment]
@philn can you give this a try? I rushed it a bit a could use another pair of :eye: 

```
flatpak install --user https://dl.flathub.org/build-repo/127299/re.sonny.Tangram.flatpakref
flatpak run --user re.sonny.Tangram//test
```

You can find WebkitGTK version in About -> Troubleshooting -> Debugging information.

**Comment by philn** [comment]
Nice, seems to work and GTK4 / adw wowness :) Only small nit maybe add some spacing between icon and tab title?

image

I can gst-inspect va in the shell now, but as its rank is 0, i need to set  this env var `GST_PLUGIN_FEATURE_RANK=vah264dec:MAX` with flatseal and I'll be all set. Thanks!

**Comment by philn** [comment]
Ah, one bug, I added a new tab (to time.is), clicked save, the tab appeared in the list just fine, but the add popup can't be closed, like at all, even click on the cancel button has no effect :(

**Comment by philn** [comment]
Doesn't seem to happen on all websites, for instance igalia's website worked, but for time.is and feedly the issue happens and i have to kill the app.

**Comment by sonnyp** [comment]
I can reproduce – but only the second time I add a tab (any url). I will fix it – thanks.

BTW I just noticed that this is the first release on GTK4 / libadwaita - I completely forgot previous releases were on the `gtk3` branch. I'm not 100% sure WebKit + GTK4 is ready for prime time, I think it still breaks for nVidia users. Do you have an opinion on that?

**Comment by sonnyp** [comment]
Still seems to be an issue https://bugs.webkit.org/show_bug.cgi?id=228268 

I will rebase onto the gtk3 branch – sorry, no adw wowness just yet :)

**Pull request merged**
