### PR TITLE
Update to GNOME 43 runtime

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by sonnyp** [comment]
Thanks — unfortunately—that's a breaking change for Tangram.

```
sonny@porygon ~ [1]> flatpak run re.sonny.Tangram//test

(gjs:2): Gjs-CRITICAL **: 22:12:54.153: JS ERROR: Error: Requiring WebKit2, version 4.0: Typelib file for namespace 'WebKit2', version '4.0' not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:14:24
@gi://WebKit2?version=4.0:3:25
```

I will update the runtime as part of the next release

**Comment by philn** [comment]
lol i was just typing the same :)

**Comment by philn** [comment]
My main motivation for upgrading is that in the 43 runtime the GStreamer va plugin is usable, so the UX is much nicer than the very buggy openh264 plugin...

**Comment by sonnyp** [comment]
@philn that's nice - let me see if I can get this done quickly

**Pull request closed without merging**
